### ISSUE TITLE
Supporting other server versions

### ISSUE THREAD

**Issue by tom2208** [tom2208/ChestCleaner#10]
At the time ChestCleaner just works for server versions 1.13, 1.14 and 1.15 (maybe 1.16). A support for 1.7, 1.8, 1.9, 1.10, 1.11, 1.12 would be great.

**Comment by leanNiki** [comment]
One Problem with versions < 1.13 is that they use Legacy Materials. That means the blocks/items have different names, eg <1.13:workbench >=1.13:crafting_table
Also if we dont specify "api-version" in plugin.yml, the server may initialize Legacy Material Support, and all blocks/items get the legacy names, also in server versions >= 1.13
So the evaluators would work differently, especially the sortingListEvaluator, where the default list only contains non-legacy materials.

**Comment by leanNiki** [comment]
A bigger problem is that all new Blocks (eg. mossy cobble slabs) are of type Material.AIR which has a MaxStackSize of 0. So the getFullStacks method won't work, since it uses maxStackSize. Also the blocks cant be sorted, because they all have the name AIR. In the current implementation the new blocks get deleted if we don't specify api-version >= 1.13, which we certainly do not want.

**Comment by tom2208** [comment]
We will not implement that by now. Maybe this issue gets reopened in the future.
