### ISSUE TITLE
Dupe bug incompability with EnchantGUI

### ISSUE THREAD

**Issue by blek-id** [tom2208/ChestCleaner#34]
Hi there, I have a plugin called EnchantGUI that turns your enchanting table into a GUI system. When players right clicked the enchanting table with an iron hoe, it would dupe their item because the plugin thinks that they're clicking a container.

Can I request it so that on the PlayerInteractEvent, you check if it's a container? (Chest, Shulker box, Ender Chest, Trapped Chest, Dispenser, etc?) Currently I've removed the plugin and I'll wait till this issue is fixed

**Comment by tom2208** [comment]
Try to set the openEventMode to false: /cleaningitem openEvent false
An explanation for this command you can find here: https://github.com/tom2208/ChestCleaner/wiki/Cleaningitem-2.0#openevent

If you want the openEventMode = true because of it's benifits you can also use the blacklist: 
https://github.com/tom2208/ChestCleaner/wiki/Blacklist-2.0

/blacklist inventory add
Just hold an enchating table while executing this command.
