### ISSUE TITLE
When auto re-filling seeds, wheat goes into the hand instead.

### ISSUE THREAD

**Issue by wm-b** [tom2208/ChestCleaner#50]
When a player is placing seeds and runs out of the stack, if they have wheat and seeds in their inventory, wheat goes into their hand instead of more seeds.

It would be more helpful if wheat and seeds were separate in this way so that wheat only goes to the hand if you run out of wheat, and seeds only go to the hand if you run out of seeds.

**Comment by tom2208** [comment]
Should be easy to fix, thank you for the report.

**Comment by tom2208** [comment]
The issue got fixed. https://github.com/tom2208/ChestCleaner/commit/322cad8fcf483fd70a1514826cab21c1c48496bd

The issue was: some items are not equal (in their material) to their placed block
Example a torch you place on a wall is not a "TORCH" it is a "WALL_TORCH".
This issue is now fixed for a ton of items.
